%******************************************************************
%*            Institut für Dynamik und Schwingungen               *
%*      Modellierung und Simulation in der Fahrzeugtechnik        *
%*                           Labor                                *
%******************************************************************
%
% Callbackfunktion zum Öffnen eines Fensters, in dem Einstellungen für das
% Basismodul verändert werden können.
% Aufbau dieser Datei:
%   1. Struktur laden.
%   2. Figure öffnen und Oberfläche gestalten.
%   3. Callbackfunktion zum Schließen der Figure.

function Mod_Basis_Einstellungen(~,~)
%   1. Erforderliche Struktur laden. Da in dieser Datei der Name der 
%   Hauptfigure nicht bekannt ist wird "gcf" verwendet. Damit ist es 
%   möglich sich auf die aktuelle Figure zu beziehen. Da der Button zum 
%   Öffnen der Einstellungen sich auf der Hautpfigure befindet ist es nicht
%   möglich, dass eine Verwechselung verschiedener Figures stattfindet.
% 
%   Beim Laden von Daten mit "getappdata" ist es möglich einen neuen und nur
%   für diese Datei gültigen Namen zu vergeben. Es ist jedoch
%   übersichtlicher in jeder Datei den gleichen Variablennamen wieder zu
%   verwenden.

% Handle der Hauptfigure auslesen
fig_ID = findobj(groot,'Name','Hauptfenster');

Parameter = getappdata(fig_ID,'Parameter');
% Ausblenden der Hauptgui, solange Einstellungen eingeblendet
set(fig_ID,'Visible','off');

%% 2. Figure öffnen und Oberfläche gestalten
fig_Basis = figure;
fig_Basis.Name = 'Eigenschaften des Basismoduls';
fig_Basis.Position = [480 200 660 460];
fig_Basis.Resize = 'off';
fig_Basis.MenuBar = 'none';
% Aufrufen Buttonfunktion zum Schließen bei Beenden über X (rechts oben)
set(fig_Basis,'CloseRequestFcn',{@Schliessen});
setappdata(gcf,'Parameter',Parameter);

%% Panel zur Erstellung eines Bereichs der Fahrzeuggeometrie
Panel_Geometrie = uipanel('Parent',fig_Basis,'Title','Fahrzeuggeometrie',...
    'FontSize',12,'Units','pixel','Position',[10 300 300 150],...
    'Tag','Mod_Basis<Panel.Fahrzeuggeometrie');

% Radstand
% Textfeld Radstand
uicontrol('Parent',Panel_Geometrie,'Style','text','Position',[5,90,200,20],...
    'String', 'Radstand [m]:','FontSize',11,'HorizontalAlignment','left');
 % Editfeld Radstand
uicontrol('Parent',Panel_Geometrie,'Style','edit','Position',[210,90,80,20],...
    'FontSize',10,'String', num2str(Parameter.Mod_Basis.l),...
    'Tag','Mod_Basis<Edit.Radstand-l','Callback',@Aenderung_Einstellungen);

% Schwerpunktlage
% Textfeld Schwerpunktrücklage
uicontrol('Parent',Panel_Geometrie,'Style','text','Position',[5,60,200,20],...
    'FontSize',11,'String','Schwerpunktrücklage [m]:',...
    'HorizontalAlignment','left');
% Editfeld Schwerpunktrücklage
uicontrol('Parent',Panel_Geometrie,'Style','edit','Position',[210,60,80,20],...
    'FontSize',10,'String', num2str(Parameter.Mod_Basis.lv),...
    'Tag','Mod_Basis<Edit.Schwerpunktrücklage-lv',...
    'Callback',@Aenderung_Einstellungen);

% Spurweite
% Textfeld Spurweite
uicontrol('Parent',Panel_Geometrie,'Style','text','Position',[5,30,200,20],...
    'String', 'Spurweite [m] :','FontSize',11,'HorizontalAlignment','left');
% Editfeld Spurweite
uicontrol('Parent',Panel_Geometrie,'Style','edit','Position',[210,30,80,20],...
    'FontSize',10,'String', num2str(Parameter.Mod_Basis.s),...
    'Tag','Mod_Basis<Edit.Spurweite-s','Callback',@Aenderung_Einstellungen);    


%% Panel zur Erstellung eines Bereichs der Fahrzeugmassen
Panel_Massen = uipanel('Parent',fig_Basis,'Title','Fahrzeugmassen',...
    'FontSize',12,'Units','pixel','Position',[10 125 300 150],...
    'Tag','Mod_Basis<Panel.Fahrzeugmassen');

% Aufbaumasse
% Textfeld Aufbaumasse
uicontrol('Parent',Panel_Massen,'Style','text','Position',[5,90,200,20],...
    'String', 'Aufbaumasse [kg] :','FontSize',11,...
    'HorizontalAlignment','left');
% Editfeld Aufbaumasse
uicontrol('Parent',Panel_Massen,'Style','edit','Position',[210,90,80,20],...
    'FontSize',10,'String', num2str(Parameter.Mod_Basis.mA),...
    'Tag','Mod_Basis<Edit.Aufbaumasse-mA','Callback',@Aenderung_Einstellungen);

% Radmasse
% Textfeld Radmasse vorne
uicontrol('Parent',Panel_Massen,'Style','text','Position',[5,60,200,20],...
    'String','Radmasse vorne [kg]:','FontSize',11,...
    'HorizontalAlignment','left');
% Editfeld Radmasse vorne
uicontrol('Parent',Panel_Massen,'Style','edit','Position',[210,60,80,20],...
    'FontSize',10,'String', num2str(Parameter.Mod_Basis.mRv),...
    'Tag','Mod_Basis<Edit.Radmasse vorne-mRv',...
    'Callback',@Aenderung_Einstellungen);

% Textfeld Radmasse hinten
uicontrol('Parent',Panel_Massen,'Style','text','Position',[5,30,200,20],...
    'String','Radmasse hinten [kg]:','FontSize',11,...
    'HorizontalAlignment','left');
% Editfeld Radmasse hinten
uicontrol('Parent',Panel_Massen,'Style','edit','Position',[210,30,80,20],...
    'FontSize',10,'String', num2str(Parameter.Mod_Basis.mRh),...
    'Tag','Mod_Basis<Edit.Radmasse hinten-mRh',...
    'Callback',@Aenderung_Einstellungen);


%% Panel zur Erstellung eines Bereichs für die Fahrzeuggeschwindigkeit
Panel_Geschwindigkeit = uipanel('Parent',fig_Basis,...
    'Title','Fahrzeuggeschwindigkeit',...
    'FontSize',12,'Units','pixel','Position',[10 25 300 80],...
    'Tag','Mod_Basis<Panel.Geschwindigkeit');

% Textfeld Fahrzeuggeschwindigkeit
uicontrol('Parent',Panel_Geschwindigkeit,'Style','text','FontSize',11,...
    'Position',[5,25,200,20],'String', 'Fahrgeschwindigkeit [m/s]:',...
    'HorizontalAlignment','left');
 % Editfeld Fahrzeuggeschwidigkeit
uicontrol('Parent',Panel_Geschwindigkeit,'Style','edit','FontSize',10,...
    'Position',[210,25,80,20],'String', num2str(Parameter.Mod_Basis.v),...
    'Tag','Mod_Basis<Edit.Geschwindigkeit-v','Callback',@Aenderung_Einstellungen);


%% Panel zur Erstellung eines Bereichs der Federsteifigkeiten
Panel_Federn = uipanel('Parent',fig_Basis,'Title','Federsteifigkeiten',...
    'FontSize',12,'Units','pixel','Position',[320 250 330 150],...
    'Tag','Mod_Basis<Panel.Federn');

% Aufbaufedern
% Textfeld Aufbaufeder vorne
uicontrol('Parent',Panel_Federn,'Style','text','Position',[5,90,230,20],...
    'HorizontalAlignment','left','FontSize',11,...
    'String', 'Aufbaufedersteifigkeit vorne [N/m]:');
 % Editfeld Aufbaufeder vorne
uicontrol('Parent',Panel_Federn,'Style','edit','Position',[240,90,80,20],...
    'String', num2str(Parameter.Mod_Basis.cAv),'FontSize',10,...
    'Tag','Mod_Basis<Edit.Aufbaufedersteifigkeit vorne-cAv',...
    'Callback',@Aenderung_Einstellungen);

% Textfeld Aufbaufeder hinten
uicontrol('Parent',Panel_Federn,'Style','text','Position',[5,60,230,20],...
    'HorizontalAlignment','left','FontSize',11,...
    'String','Aufbaufedersteifigkeit hinten [N/m]:');
% Editfeld Aufbaufeder hinten
uicontrol('Parent',Panel_Federn,'Style','edit','Position',[240,60,80,20],...
    'String', num2str(Parameter.Mod_Basis.cAh),'FontSize',10,...
    'Tag','Mod_Basis<Edit.Aufbaufedersteifigkeit hinten-cAh',...
    'Callback',@Aenderung_Einstellungen);

% Textfeld Reifenfeder
uicontrol('Parent',Panel_Federn,'Style','text','Position',[5,30,230,20],...
    'FontSize',11,'String', 'Reifenfedersteifigkeit [N/m]:',...
    'HorizontalAlignment','left');
 % Editfeld Reifenfeder
uicontrol('Parent',Panel_Federn,'Style','edit','Position',[240,30,80,20],...
    'String', num2str(Parameter.Mod_Basis.cR),'FontSize',10,...
    'Tag','Mod_Basis<Edit.Reifenfedersteifigkeit-cR',...
    'Callback',@Aenderung_Einstellungen);


%% Panel zur Erstellung eines Bereichs der Dämpferbeiwerte
Panel_Daempfer = uipanel('Parent',fig_Basis,'Units','pixel',...
    'Title','Dämpferbeiwerte','FontSize',12,'Position',[320 105 330 120],...
    'Tag','Mod_Basis<Panel.Daempfer');

% Aufdämpfer
% Textfeld Aufbaudämpfer vorne
uicontrol('Parent',Panel_Daempfer,'Style','text','Position',[5,60,230,20],...
    'HorizontalAlignment','left','FontSize',11,...
    'String','Aufbaudämpfer vorne [Ns/m]:');
 % Editfeld Aufbaudämpfer vorne
uicontrol('Parent',Panel_Daempfer,'Style','edit','Position',[240,60,80,20],...
    'String', num2str(Parameter.Mod_Basis.bAv),'FontSize',10,...
    'Tag','Mod_Basis<Edit.Aufbaudäpmferbeiwert vorne-bAv',...
    'Callback',@Aenderung_Einstellungen);

% Textfeld Aufbaudämpfer hinten
uicontrol('Parent',Panel_Daempfer,'Style','text','Position',[5,30,230,20],...
    'HorizontalAlignment','left','FontSize',11,...
    'String', 'Aufbaudämpfer hinten [Ns/m]:');
 % Editfeld Aufbaudämpfer hinten
uicontrol('Parent',Panel_Daempfer,'Style','edit',...
    'Position',[240,30,80,20],'String', num2str(Parameter.Mod_Basis.bAh),...
    'FontSize',10,'Tag','Mod_Basis<Edit.Aufbaudäpmferbeiwert hinten-bAh',...
    'Callback',@Aenderung_Einstellungen);


% Push-Button zum Akzeptieren und Schliessen
uicontrol('Parent', fig_Basis, 'Style','pushbutton',...
    'Position',[350 25 250 30], 'String', 'Akzeptieren und Schliessen',...
    'FontSize',12,'HorizontalAlignment','center','Callback',@Schliessen);
end

%% 3. Callbackfunktion zum Schließen der Figure findobj(groot,'Name','Hauptfenster')
function Schliessen(~,~)
% Die Parameterstruktur wird aus der aktuellen Figure (Eigenschaften des 
% Basismoduls) ausgelesen
Parameter = getappdata(gcf,'Parameter');
% Figure (Eigenschaften des Basismoduls) wird geschlossen
delete(gcf);
% Handle der Hauptfigure auslesen
fig_ID = findobj(groot,'Name','Hauptfenster');
% Parameterstruktur wird an die Hauptfigure angehängt
setappdata(fig_ID,'Parameter',Parameter);
% Wiedereinblenden der Hauptgui
set(fig_ID,'Visible','on');
end